### ISSUE TITLE
Not working with angular-cli

### ISSUE THREAD

**Issue by beckmeindia** [shlomiassaf/angular2-modal#134]
![angular2-modal-problem](https://cloud.githubusercontent.com/assets/17447464/16942495/f6252030-4db3-11e6-8d76-1e317960eafc.jpg)
Trying to run the modal with angular-cli fails because when we do 'ng serve' it shows and error in console  that it cannot find http://localhost:4200/node_modules/angular2-modal/....

I am following the 5 minute quickstart that was recommended using npm install.

I have also implemented the additions mentioned in issue #109 both with & without using /index

Please help.

Cheers,
Rahul

**Comment by lsiden** [comment]
Please see my [response](https://github.com/shlomiassaf/angular2-modal/issues/109#issuecomment-233428669) to #109 .

**Comment by beckmeindia** [comment]
Sure. Thank You.

Also I tried with webpack and it worked. But I am getting an "uncaught promise error" during closing the modal. 

I checked and saw it was an issue raised earlier. Is it fixed now?

**Comment by lewgun** [comment]
the same problem, do all as @lsiden suggested , but it's didn't work too.

**Comment by shlomiassaf** [comment]
@lewgun I believe @beckmeindia got it to work... so you might be missing something but we can't tell without information.

@beckmeindia I have a solution but it's in a branch with some other things that I still cant merge.

I had little time to work on the modal for the past 2 weeks, I hope I can free up some time next week.

**Comment by beckmeindia** [comment]
Sure. Would look forward to this. I have presently shifted to webpack version for a more appropriate development environment.
It works there for sure and I integrated it appropriately.

**Comment by shlomiassaf** [comment]
angular-cli is moving to a webpack based environment so we will all switch to the cli at some point

**Comment by Toadskin** [comment]
Followed the 5 quickstart with angular-cli which fails.  Then added these proposed changes, first without then with appending "index" on the import:

Updated vendorNpmFiles in angular-cli-build.js: 
    'angular2-modal/**/*.+(ts|js|js.map)'
Updated map in system-config.ts:   
    'angular2-modal': 'vendor/angular2-modal'
Added "index":
   import {MODAL_BROWSER_PROVIDERS} from 'angular2-modal/platform-browser/index'

Result:

GET http://localhost:4200/vendor/angular2-modal/platform-browser/index 404 (Not Found)

:(

**Comment by Toadskin** [comment]
We'll get used to it but Angular 2.0 is going to get a lot of push-back from application developers spending their budgets on wheel spinning and plumbing tasks.

**Comment by rajjejosefsson** [comment]
I've the same error.... and same angular-cli problem with other installations  :/

**Comment by lsiden** [comment]
I think I got it to work when I updated angular to rc.4.

**Comment by rajjejosefsson** [comment]
I dont know, Im new the Angular and only been using rc4, so it must be something else?

**Comment by shlomiassaf** [comment]
Update was made to internal import paths for better SystemJS support.

Please check version 1.1.1 (or 2.0.0-beta.2 if you want the [next version](https://github.com/shlomiassaf/angular2-modal/pull/153) coming soon)

See [this plunker](http://embed.plnkr.co/hwbmF9/) sample for v1.1.1
or [this plunker](http://embed.plnkr.co/7c0pGE/) sample for v2

**Comment by RajniShriramoji** [comment]
Hi, am getting some issue while installation itself using "npm install angular2-modal --save". Its showing something like "cant find python executable python". Am unable to understand this. Please let me know if i need to do anything more.

Am using angular2 rc5 version with angular-cli.
