### ISSUE TITLE
modal.defaultViewContainer is erroring out

### ISSUE THREAD

**Issue by nsabarisri6** [shlomiassaf/angular2-modal#276]
Hi, 

I am trying to import angular2-modal in my project.

import { Component, OnInit, ViewContainerRef, ViewEncapsulation } from '@angular/core';
import { Modal } from 'angular2-modal/plugins/bootstrap';
import { RecipeItemDetailComponent } from '../recipeitemdetail/recipeitemdetail.component'
@Component({
  selector: 'app-recipevarieties',
  templateUrl: './recipevarieties.component.html',
  styleUrls: ['./recipevarieties.component.css']
})
export class RecipevarietiesComponent implements OnInit {

  public recipeList = [{ name: 'Chicken Biriyani', image: '../assets/images/chickbiriyani.jpg' },
  { name: 'Chilly Chicken', image: '../assets/images/chillyChicken.jpg' }, { name: 'Chicken Tikka', image: '../assets/images/chickenTikka.jpeg' },
  { name: 'Mushroom masala', image: 'https://i.ytimg.com/vi/dPLw0rX-QO0/maxresdefault.jpg' },
  { name: 'Chilli Prawns', image: 'http://www.cookingandme.com/wp-content/uploads/2013/03/8600732154_2e7a116538_z.jpg' }];
  public cart = [];
  constructor(vcRef: ViewContainerRef, public modal: Modal) {
     modal.defaultViewContainer = vcRef;
  }
  selectRecipe(recipe) {
    this.modal.alert()
      .size('lg')
      .showClose(true)
      .title('A simple Alert style modal window')
      .body(`
            <h4>Alert is a classic (title/body/footer) 1 button modal window that 
            does not block.</h4>
            <b>Configuration:</b>
            <ul>
                <li>Non blocking (click anywhere outside to dismiss)</li>
                <li>Size large</li>
                <li>Dismissed with default keyboard key (ESC)</li>
                <li>Close wth button click</li>
                <li>HTML content</li>
            </ul>`)
      .open();    
  }
  ngOnInit() {
  }

}
But I get error saying 

Property 'defaultViewContainer' does not exist on type 'Modal

I also followed your earlier workaround and included

<span defaultOverlayTarget></span>

But still no use. I get the same error. When I used,

modal.overlay.defaultViewContainer = vcRef;  ==> I can see the modal, but not the content.

(This idea was mentioned by another guy in the same thread)

Reference:

https://github.com/shlomiassaf/angular2-modal/issues/210

Please help me. 

Thanks,
Sabarisri N

**Comment by SilverJan** [comment]
Facing the same issue in v3.0.1.

**Comment by thekeldeo** [comment]
i got that error too, and still get error when add 
modal.overlay.defaultViewContainer = vcRef;

==> Property 'defaultViewContainer' does not exist on type 'Overlay'.

**Comment by bopro** [comment]
the same error

**Comment by karocksjoelee** [comment]
same error here as well

**Comment by thekeldeo** [comment]
hey i just fixed by included <span defaultOverlayTarget></span> to main template and remove modal.overlay.defaultViewContainer = vcRef; or overlay.defaultViewContainer = vcRef;

**Comment by karocksjoelee** [comment]
@thekeldeo  Can you explain what to "included to main template" ?

**Comment by thekeldeo** [comment]
here is my app.component.ts

**Comment by karocksjoelee** [comment]
@thekeldeo  Thank you ~ but mine still not working . Maybe because I've used module lazyloading ??

**Comment by SilverJan** [comment]
@thekeldeo Unfortunately not working for me either.

.open() on a modal instance causes ~20s ideling in the whole view.

**Comment by arkwl** [comment]
It's not working for me either. Any other fixes?

**Comment by arkwl** [comment]
@nsabarisri6 have you tried to reproduce the error on plunker?

**Comment by ronh73** [comment]
I found the solution for this problem here, provided by romanchuk:
https://github.com/shlomiassaf/angular2-modal/issues/278

I have created a Github repo in which I applied this solution (Git clone it and run _npm run ng serve_ from the root directory of the project):
https://github.com/ronh73/modalng2

The key thing here is to remove the line _modal.overlay.defaultViewContainer = vcRef;_ from the constructor and instead of that add some code to the app.module.ts.

**Comment by ronh73** [comment]
Unfortunately I can not add bootstrap to my solution.

**Comment by developersatish** [comment]
```
error TS2339: Property 'defaultViewContainer' does not exist on type 'Overlay'.

91     overlay.defaultViewContainer = vcRef;
```
