### ISSUE TITLE
custom component in .body()

### ISSUE THREAD

**Issue by harshpatel79** [shlomiassaf/angular2-modal#277]
Hey can we add custom components in .body() method.

**Comment by RevProg** [comment]
Same issue

**Comment by zaiz91** [comment]
+1

**Comment by Jaskar14** [comment]
+1

**Comment by segalz** [comment]
I need it too :(

**Comment by shlomiassaf** [comment]
This is a change to the bootstrap plugin, if anyone wants to give it a shot I will gladly accept PRs.

If not I will try to find time but I'm pretty busy now

**Comment by FredLoney** [comment]
A work-around is to set the modal body to the inner HTML of a hidden child component as shown in [this example](https://plnkr.co/edit/xJdk9F?p=preview). A refinement of this is to make the child a [dynamic component](https://angular.io/docs/ts/latest/cookbook/dynamic-component-loader.html).

**Comment by F3L1X79** [comment]
+1

**Comment by ohgasauraus** [comment]
>A work-around is to set the modal body to the inner HTML of a hidden child component as shown in this example. A refinement of this work-around is to make the child a dynamic component.

I have tried this, however i encounter the following error "_Argument of type 'SafeHtml' is not assignable to parameter of type 'string'._" for this statement `.body(this.child.innerHTML)`.

Am i using the wrong version of angular2-modal?

**Comment by FredLoney** [comment]
SafeHtml is the tag interface Angular puts on the bypassed string. Perhaps the compile error you show is because of stronger type-checking. At any rate, the solution is to wrap the bypass result in a String() conversion. The example is updated with this improvement.

Please note that the example is only a crude work-around for this particular issue, as indicated in the ChildComponent comment. My project is migrating from angular2-modal to the new ng-bootstrap modal. ng-bootstrap modal has the embedded subcomponent capability. However, this is a small part of a larger CSS migration to Bootstrap 4, which is a significant undertaking probably unwarranted for the modal alone.

**Comment by hicham-zreik** [comment]
@FredLoney please can you explain what do you mean by "wrap the bypass result in a String() conversion" ?

**Comment by FredLoney** [comment]
cf. the example link above:

    get innerHTML(): string {
       // TODO - remove this work-around when the aforementioned issue
      // is fixed.
      let html = this.elementRef.nativeElement.innerHTML;
      let raw = this.sanitizer.bypassSecurityTrustHtml(html);
      return String(raw);
    }

**Comment by hicham-zreik** [comment]
@FredLoney  thank you so much the error has solved but I have another error "Cannot read property 'innerHTML' of undefined",Did you think this error is because this issue or issue in my project ?

**Comment by hicham-zreik** [comment]
Sry I am junior web developper and I am beginner in angular 2 but I have searched a lot and my probleme is the ViewChild(ChildComponent)not resolving component,any help ??
Thank in advance

**Comment by FredLoney** [comment]
I'm afraid I don't understand the question. Perhaps you should post it with a plunkr example on StackTrace with the [angular2] tag.

**Comment by Eencsio** [comment]
@hicham-zreik  maybe you forgot to add the tag of your child component in the parent template. See the plunker example in file app.component at line 12, and in file childcomponent.ts at line 6

**Comment by Eencsio** [comment]
@hicham-zreik  also if you have some input tags in the child component, when you append the body of the modal, instead of wrapping the innerHTML in a string as @FredLoney  did, you can append it like `.body(this.child.innerHTML as any)` and there will be no error in the bidding, but I don't know the implications of doing it in this way
