### ISSUE TITLE
Modal not showing when used with Bootstrap V4

### ISSUE THREAD

**Issue by nbckr** [shlomiassaf/angular2-modal#280]
I spent some time wondering why the modal would not show on screen, now I found out and I want to share my insights in case anyone has the same problem.

The reason was a breaking change in Bootstrap 4.0.0-alpha.6. In earlier Versions, class="fade in" on the modal caused it to a) be hidden and b) smoothly appear. It seems that the "in" class has now been renamed to "show". angular2-modal gives its element the classes "fade in" however, so they just disappear.

### Workaround

Override styles:

```
.fade.in {
  opacity: 1;
}
.modal.in .modal-dialog {
  -webkit-transform: translate(0, 0);
  -o-transform: translate(0, 0);
  transform: translate(0, 0);
}
.modal-backdrop.in {
  opacity: 0.5;
}
```

**Comment by achimha** [comment]
I can confirm the issue and the workaround. With Boostrap 4.0.0-alpha.6, calling the `open` method makes the application appear to hang, scrolling is disabled but the screen content does not change. This is due to the modal being present but not visible.

**Comment by shlomiassaf** [comment]
Can someone post a plunker for this?

**Comment by dimejy2** [comment]
I can confirm that the same issue occurs, however I had to include important tags in order to override the default css. Here's the revised version.

```
.fade.in {
  opacity: 1;
}
.modal.in .modal-dialog {
  -webkit-transform: translate(0, 0);
  -o-transform: translate(0, 0);
  transform: translate(0, 0);
}

.modal-backdrop .fade .in {
  opacity: 0.5 !important;
}


.modal-backdrop.fade {
    opacity: 0.5 !important;
}
```

**Comment by jsnkelvin** [comment]
@dimejy2 code works well, but there is some delay on background fading when closing the modal. 
maybe because the fade out got replaced too.

is there any way to fix that?
thanks!

**Comment by ravtakhar** [comment]
This is working well for the time being, but this should be included in the actual package itself? Is someone working on creating a pull-request?

**Comment by dan-nawrocki** [comment]
@shlomiassaf here is a plunker showing the problem: http://plnkr.co/edit/b44cBG0LdXTS7jMlXsfA. 

I suspect this issue is related to #217. The delay noted in this ticket appears to be caused by the animation effect callback never being triggered as described in the other ticket; this also causes the modal-open class to be "stuck" on the <body>.

**Comment by shabbir-dhangot** [comment]
Hi @dan-nawrocki @dimejy2 @ravtakhar @jsnkelvin @nbckr 

I see one small bug with the code. I implemented it using custom css. I have no problem with animation. 

Problem :
When there is long content available with scroll bar user can scroll it. but after any dialog box open scrollbar gone and content freeze there.

For Demo I created from same plunker
http://plnkr.co/edit/vpisqf0onct946qZFti6?p=preview

open dialog and scrollbar will gone. 

Please help me with this.

**Comment by dan-nawrocki** [comment]
@shabbir-dhangot the ```modal-open``` class is getting stuck on the ```<body>```; this is why the scrollbars don't come back. You can modify the modal.js file as mentioned in my previous comment as a workaround.

**Comment by dan-nawrocki** [comment]
OK @jsnkelvin @shabbir-dhangot:

I managed to get rid of the delay given the hint from my workaround. The ```combineLatest``` RXJS method waits for a ```myAnimationEnd$``` from **both** the ```backdrop``` and ```container```. The issue with @dimejy2's CSS workaround looks like it prevents the animation on the ```modal-background``` by setting the opacity to 0.5 for both ```.fade``` and ```.fade .in```. What is working for me is @nbckr's original snippet:

```
.fade.in {
  opacity: 1;
}

.modal.in .modal-dialog {
  -webkit-transform: translate(0, 0);
  -ms-transform: translate(0, 0);
  -o-transform: translate(0, 0);
  transform: translate(0, 0);
}

.modal-backdrop.in {
  opacity: 0.5;
}
```

And a plunker: http://plnkr.co/edit/b44cBG0LdXTS7jMlXsfA

@shlomiassaf, it looks like the only changes for bootstrap 4 (alpha 6  at least) is to update any instances of the ```in``` class to ```show``` and this workaround will no longer be necessary. I can create a PR if you're interested.

**Comment by locohost** [comment]
None of the bootstrap4-alpha6 CSS fixes above work for me. I put them app.component.css, didn't fix. I have to install bootstrap3.3.7 to get the modal working. Why?

**Comment by locohost** [comment]
Ok if you put the CSS above in the base styles.css, it almost works. Modal shows, but background does not dim.

**Comment by maksim-marholin** [comment]
I can confirm this issue for Bootstrap 4 alpha 6, but we didn't have it for alpha 4.

**Comment by shabbir-dhangot** [comment]
@maksim-marholin @locohost  use modal by ng bootstrap. Its working fine for me. https://ng-bootstrap.github.io/#/components/modal

**Comment by rolandoldengarm** [comment]
@shabbir-dhangot we're using Angular2-modal as it allows you to create modals from TypeScript with fluent API. That's not possible with ng-bootstrap's version.

**Comment by constsync** [comment]
I found this solution to work for me. Pass this object as an argument to _modalService.open(component, { size: "lg", windowClass: "in"});

**Comment by JhonnyHRocha** [comment]
Did you add this to your HTML?

```
<!-- Enable bootstrap 4 theme -->
<script>window.__theme = 'bs4';</script>
```
Thats currently required for v4

**Comment by PeterKutschera** [comment]
Works for me. 

To get the original workaround working (I copied the CSS into my app.component.css) I needed to disable ViewEncapsulation in app.component.ts.

See "Disable CSS Encapsulation" at https://coryrylan.com/blog/css-encapsulation-with-angular-components for how to do this.

**Comment by hit3ham** [comment]
please . i am a beginner in web coding , i have the same problem Modal not showing when used with Bootstrap V4,,, i saw the code of styles that you share and some people say it works , but actually i don't know where to past it in my code , should it be inside <style></style>, thanks in advance

**Comment by JavierT** [comment]
Indeed both works for me. But why I can't find any references to the theme in the bootstrap 4 website? If it is required it should be said clearly.

```
<!-- Enable bootstrap 4 theme -->
<script>window.__theme = 'bs4';</script>
```

Btw, adding this, what are exactly doing? 

Thank you

**Comment by shlomiassaf** [comment]
Thanks to @dan-nawrocki

**Comment by SthatycSoul** [comment]
Works for me, I had a problem cause I made a port of a proyect than I'm working with pure bootstrap 4, and need to do some changes on the versions...

Thank you so much in advance, regards.

**Comment by hamzox** [comment]
@nbckr Thanks mate.

**Comment by Fintasys** [comment]
I still needed to use the workaround provided in my case to make it work with Bootstrap 4 official release.

**Comment by sagarjhaa** [comment]
Thanks @nbckr.

**Comment by Nik-Lz** [comment]
So i basically replaced .show with .in and placed the exact same values the OP noted. Still doesn't work.

**Comment by JoshuaCaputo** [comment]
Also experiencing this issue:
4.1.3/css/bootstrap.min.css
4.1.3/js/bootstrap.min.js

The workaround does seem to fix this confict. mabe fade should be something not some widespread... it sort of curtains...

`class="modal curtain"`

**Comment by castlejiant** [comment]
@JoshuaCaputo Yes, But there is nothing to do with curtain. Even if you remove class (curtain), the modal will appear. If we use the given modal examples in Bootstrap 4, it works. But when we use the modal examples for Bootstrao 4.1.3, it doesn't works. Please raise a ticket for this issue.

**Comment by Eivyses** [comment]
Having same problem with 4.1.3 version. NgbModal windows won't show. Need to use bootstrap 4.0.0-alpha.6 for it to work.

**Comment by Howzilla** [comment]
I have this working with Bootstrap 4.3.1

- Create a new css file such as Overrides.css
- Put the following code in it:

.fade.in {
    opacity: 1 !important;
}

.modal.in .modal-dialog {
    -webkit-transform: translate(0, 0) !important;
    -o-transform: translate(0, 0) !important;
    transform: translate(0, 0) !important;
}

.modal-backdrop .fade .in {
    opacity: 0.5 !important;
}

.modal-backdrop.fade {
    opacity: 0.5 !important;
}

- Load this new file LAST in your Bundles.cs or whatever mechanism you are using to load support files

This is very similar to what you see above BUT the "!important" attribute has been added to some of the items.

**Comment by narfie** [comment]
I also have the same issue with Bootstrap 4.3.1

The custom CSS provided by @Howzilla works to fade the background, but the modal still doesn't show up.

If I remove ".fade" class from the modal, the modal opens up, but the background is black.

I'm baffled by this.  It seems like an obvious bug.  As far as I can tell I don't have any other scripts conflicting with this.

**Comment by ryanki1** [comment]
Thanks for the headsup @nielsboecker as this is also unsurprisingly a problem with bootstrap 3 framework.. to get modal to show use following scss based on Niels' post:
```
.fade.show {
  opacity: 1 !important;
}

.modal.show .modal-dialog {
  -webkit-transform: translate(0, 0) !important;
  -o-transform: translate(0, 0) !important;
  transform: translate(0, 0) !important;
}

.modal-backdrop .fade .show {
  opacity: 0.5 !important;
}

.modal-backdrop.fade {
  opacity: 0.5 !important;
}
```
.. and rather use component to open modal as the templateRef doesn't seem to work.. come on ngx-bootstrap developers you claim your ngx framework is re bootstrap backwards compatible :-)
